### ISSUE TITLE
'file' tag/function

### ISSUE THREAD

**Issue by Lunatrius** [Lunatrius/InGame-Info-XML#18]
The basic idea is that this reads text and outputs that as a single line.

Optionally it could take additional arguments to do advanced tweaking/searching with regex to extract important bits of data.

**Comment by bspkrs** [comment]
Just make sure it is limited to the MC directory. Otherwise some asshole is going to ship a modpack with a custom config that shows something you DON'T want on your screen.

**Comment by Lunatrius** [comment]
Hmm... good point.
