### ISSUE TITLE
Enhancements: Potion-Type and pulsing timer

### ISSUE THREAD

**Issue by scyfar** [Lunatrius/InGame-Info-XML#23]
It would be nice if there was an option to display harmful and harmless postions separate from each other. Currently there is no way to differentiate between those two types.

Maybe the ability to compare strings would be a possible solution, a boolean variable would be easier to use however.

Additionally it would be nice to have the ability to let fading potion effects blink/pulse. The start ticks/time should be configurable.

**Comment by Lunatrius** [comment]
Check the code and there is currently no way to check whether a PotionEffect is harmful or harmless. If there was a way to do it I could just add a tag for `potionharmful`. The effects themselves are applied directly via the `potion.performEffect(entity)`.

Might not be easy to do blinking/pulsing. All the text is rendered in a single run and it might affect other text. Alternatively, a "blinking" effect is already possible by prepending this to each potion effect:
```xml
<min>
  <var>potiondurationticks0</var>
  <num>200</num> <!-- start when (20 * 10 seconds = 200) ticks are left on the potion -->
  <op>
    <str>ge</str>
    <modi>
      <var>potiondurationticks0</var>
      <num>20</num>
    </modi>
    <num>0</num>
    <num>5</num>
    <num>10</num>
    <num>15</num>
    <var>red</var>
    <var>orange</var>
    <var>yellow</var>
    <var>white</var>
  </op>
  <str/>
</min>
```

I haven't tested it, but this should make the potion turn white -> yellow -> orange -> red over a second, for the last 10 second.

**Comment by bspkrs** [comment]
https://github.com/bspkrs/StatusEffectHUD
just sayin'

**Comment by Lunatrius** [comment]
That too, does a better job at this specific task. :P

**Comment by scyfar** [comment]
> **bkpkrs:**
> https://github.com/bspkrs/StatusEffectHUD
> just sayin'

Thanks for the hint. Just did not find this mod for 1.8 as it is not labeled on the forums nor listed in the MCF Mod List ;)

I will check it out.

**Comment by bspkrs** [comment]
Oh yeah... I guess I forgot to change the thread titles.

**Comment by Lunatrius** [comment]
Going to close this then.
