### ISSUE TITLE
Something went wrong!

### ISSUE THREAD

**Issue by Chefbarbie** [Lunatrius/InGame-Info-XML#25]
This is what I get anytime I attempt to load InGameInfo.txt. Here's what's inside when I attempt "/igi load InGameInfo.txt": http://pastebin.com/nxF8uD0a

**Comment by Lunatrius** [comment]
The position modifiers can't be the only thing in a single line. [This config](https://gist.github.com/5a07ad46b4e029872f66) loads up fine.
