### ISSUE TITLE
Glitching Texts whenever I hover over an Aura Node

### ISSUE THREAD

**Issue by gabor6505** [Lunatrius/InGame-Info-XML#27]
*If I hover over a Thaumcraft Aura Node, every text on the screen added by CMM, gets bright. I am not sure if this is a problem with Thaumcraft, OptiFine, or maybe WAILA, but I will test it without OptiFine and WAILA if you need it.*
I tested if I disable WAILA, the brightness goes away to normal, so the problem is maybe with WAILA. I will report / reference this to them too.

Screenshots:
![2015-07-24_11 32 26](https://cloud.githubusercontent.com/assets/12859334/8871730/c8f837ec-31f7-11e5-8964-28ebb3804150.png)
![2015-07-24_11 32 28](https://cloud.githubusercontent.com/assets/12859334/8871750/e684fa16-31f7-11e5-90e4-8a0ad25bee1b.png)

Minecraft Version: 1.7.10
Lunatrius Core Version: 1.1.2.21
InGame Info XML Version: 2.8.1.80

If you need more info, forge log, modlist, tell me.

**Comment by Lunatrius** [comment]
Yeah, that would be WAILA and/or Thaumcraft not resetting the OGL state (GL_BLEND/GL_LIGHTING I assume). I'll see if I can do anything about it.

**Comment by gabor6505** [comment]
Okay, Thanks! I already posted this issue on the WAILA Bug Tracker too. :smile:

**Comment by Lunatrius** [comment]
The issue doesn't appear in a minimal setup of WAILA, IGI and Thaumcraft. Seems to be something else. Will be a pain to test this...

**Comment by Lunatrius** [comment]
Should be fixed in db588c18ec4002aee82b98794d9421c5c559ab00. Try the latest build once it's up (about 10 minutes from this comment).

If the issue persist feel free to re-open the issue.
