### ISSUE TITLE
NoSuchMethodError: FMLControlledNamespacedRegistry

### ISSUE THREAD

**Issue by riseon** [Lunatrius/InGame-Info-XML#30]
READ THIS
---
Your game will crash with `java.lang.NoSuchMethodError: net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry` if you use Forge 1817 or newer. To avoid this please **use Forge 1816 or earlier**. The long story short, Forge 1.9 is rapidly changing things and I don't feel like pushing out *recompiles* for stuff that works in older versions.

*Having multiple, recompiled version would increase the amount of crashes due to an invalid Forge version - it's just easier this way.* Once we get 1.9.3 things should hopefully be stable again.
-- @Lunatrius

---

Can't get it to load with forge 12.16.0.1819 or 12.16.0.1834.  I got it to load with 12.16.1809 but I needed a newer version for other mods.  Crash report below.

[crash-2016-04-03_21.43.22-client.txt](https://github.com/Lunatrius/InGame-Info-XML/files/201680/crash-2016-04-03_21.43.22-client.txt)

**Comment by ryanjo1982** [comment]
I am also getting this error. I've included the crash log for clarity.

http://paste.ee/p/e3AnI

**Comment by Lunatrius** [comment]
Similar to Lunatrius/Stackie#7, most likely requires a recompile. Given how unstable Forge currently is (unstable as in 'things are changing') I'd suggest to revert back to Forge 1816 for the time being.

**Comment by ryanjo1982** [comment]
Ok. Thank you for the info. I think I will to add it to my pack until it is supported by a more up-to-date version of forge.

**Comment by Lunatrius** [comment]
This is one of the reasons why I delayed the 1.9 release for a week initially - 1.9 Forge is rapidly updating and breaking some things in the process. Just having to recompile the same version for different Forge versions will get confusing really quick.

Forge will be out relatively soon for 1.9.2 anyway, so might as well just wait for that while fixing any bugs that have to be fixed.

**Comment by ryanjo1982** [comment]
I can see how that would be a big headache. Thanks for all the work you are doing.

**Comment by riseon** [comment]
Thank you for the information!

**Comment by JonnyBrando** [comment]
Same problem here, updated forge for new mod support, and broke IngameInfoXML.

I built a new copy of IngameInfoXML on the latest forge which is working.

https://dl.dropboxusercontent.com/u/14381275/InGameInfoXML-1.9-2.8.1.git-forge12.16.0.1863-universal.jar

**Comment by Lunatrius** [comment]
Fixed in `2.8.1.82`.
