### ISSUE TITLE
Issue: crashing on startup

### ISSUE THREAD

**Issue by OPlurker1005** [Lunatrius/InGame-Info-XML#31]
**Mod version:** 1.9-2.8.1.81-universal
**Forge version:** 12.16.0.1854
**Operating system:** Windows 8.1
**Mod list:**
  * ArmorHud-1.8.9-2.0.1
  * ArmorPlus1.7.14(1.9)
  * BetterBedrockGenerator-1.9.0-3.0.0
  * BetterBuildersWands-0.5.4-1.9r106+81accd9
  * Bookshelf-API-1.9-3.0.4
  * capsule-1.9-1.1.4
  * Chameleon-1.9-2.1.3
  * chiselsandbits-9.11
  * ChunkAnimator-MC1.9-1.1
  * deepresonance-1.9.0-1.1.4beta26
  * easybreeding-1.9-1.9-4.0.1
  * ElecCore-1.9-1.4.261
  * EmeraldItems v1.9-0.7
  * EnderCompass-1.9-1.2.3
  * endercrop-1.9-1.2.1811
  * FastLeafDecay-MC1.9-1.2
  * Gravestone Mod 1.2.2
  * InGameInfoXML-1.9-2.8.1.81-universal.jar
  * InventoryTweaks-1.61-dev-45
  * ironchest-1.9-6.0.132.776
  * JACB-1.9-1.0.6
  * jei_1.9-3.2.8.182
  * journeymap-1.9-5.1.6b1-unlimited
  * JustEnoughResources-1.9-0.4.3
  * LemonsSimpleTeleporters-1.1.1
  * LLOverlayReloaded-1.0.7-mc1.9
  * LunatriusCore-1.9-1.1.2.33-universal
  * mcjtylib-1.9.0-1.8.1beta13
  * ModularSystems-1.9-3.0.2
  * morefuelsmod-1.9-v1.3.1
  * MouseTweaks-2.6.2-mc1.9
  * NeoTech-1.9-3.0.5
  * OptiFine_1.9.0_HD_U_B1
  * OreDictionaryConverter-1.8.0
  * Packing Tape-0.5.1
  * QuantumStorage-1.9-3.0.0
  * RandomThings-MC1.9-3.6.9
  * RealTimeClock-1.9-0.6.1
  * RebornCore-1.9-2.0.4.46-universal
  * refinedstorage-0.5.3
  * Reliquary-1.9-1.3.1.279
  * rftools-1.9.0-4.23beta39
  * Ruins-1.9
  * SoulShards-TOW-1.9-2.3.8-23
  * StorageDrawers-1.9-3.1.4
  * Trashcans-1.9-2.0.2
  * UncraftingGrinder-1.9-1.0.4
  * VeinMiner-1.9_0.31.5.forgePost18010
  * WIT-1.9-1.0.13-27

**Crash report:** http://pastebin.com/KtkLuesY

**Comment by Lunatrius** [comment]
#30
