### ISSUE TITLE
Crash report by Natural_Body

### ISSUE THREAD

**Issue by Dosbound** [Lunatrius/InGame-Info-XML#32]
**Mod version:** 1.9-2.8.1.81-universal
**Forge version:** 1.9-12.16.0.1859-1.9(Custom)
**Operating system:** -- Windows 10
**Mod list:**
  * Baubles-1.9-1.2.0.0
  * BiomesOPlenty-1.9-4.0.0.2003-universal
  * Chameleon-1.9-2.1.3
  * FastLeafDecay-1.9-1.6
  * InGameInfoXML-1.9-2.8.1.81-universal
  * LunatriusCore-1.9-1.1.2.33-universal
  * MouseTweaks-2.6.2-mc1.9
  * ProgressiveAutomation-1.9-1.6.38
  * RandomThings-MC1.9-3.6.9
  * StorageDrawers-1.9-3.1.4
  * VeinMiner-1.9_0.31.5.forgePost18010
  * Waila-1.7.0-B2_1.9

**Crash report:** 
http://pastebin.com/gP5WLJmQ

**Comment by Lunatrius** [comment]
#30
