### ISSUE TITLE
Minecraft crashes on startup

### ISSUE THREAD

**Issue by harleypig** [Lunatrius/InGame-Info-XML#33]
**Mod Version:** InGameInfoXML-1.9-2.8.1.81-universal.jar
**Forge Version:** 1.9-forge1.9-12.16.0.1864-1.9.jar
**Operating System:** Linux 3.19.3
**Mod list:**
  * InGameInfoXML-1.9-2.8.1.81-universal.jar
  * LunatriusCore-1.9-1.1.2.33-universal.jar

**Crash report:** https://gist.github.com/harleypig/99656b60b136b4b85e03bcf827acf474

**Comment by Lunatrius** [comment]
#30 read the note at the top
