### ISSUE TITLE
"exhaustion" tag not working

### ISSUE THREAD

**Issue by Kzitold** [Lunatrius/InGame-Info-XML#36]
The numbers for the "exhaustion" tag isn't changing when I do stuff. Isn't it supposed to show how quickly I'm draining my sustenance or whatever you call the food meter?

**Comment by Lunatrius** [comment]
Somehow missed the issue. Checked it and after a quick look at the behavior it might be possible that the client no longer keeps track of the food exhaustion level, making it impossible to display that information.

**Comment by Lunatrius** [comment]
The value for food exhaustion no longer syncs to the client, making it impossible to show the expected value. This was always a hidden attribute and it appears that Mojang removed the value from the watch list.
