### ISSUE TITLE
"slimes" tag not respecting chunks' borders

### ISSUE THREAD

**Issue by hhiru** [Lunatrius/InGame-Info-XML#38]
I made a video to make the problem more clear, am I missing something or maybe there is something not working properly? I'm on 1.10.2 and using the latest version of your mod.

https://youtu.be/27z8u2XAmFM

**Comment by Lunatrius** [comment]
Is the area in a swamp biome?

**Comment by hhiru** [comment]
uhm yes.. so that's why.. is there no why to distinguish or excluding swamp biomes as slime chunks? it is well known slimes spawn there with full moon so maybe you can omit this information in swamps? I don't know if this is possible

**Comment by Lunatrius** [comment]
It was a request from a long time ago, but the tag list was never updated accordingly. I'll most likely add a new tag `slimechunk` or something along the lines of that.

**Comment by hhiru** [comment]
Thanks for your help then! I love your work :) p.s. I sent you a tweet about a possible localization for this mod, just in case you are interested in adding more languages

**Comment by Lunatrius** [comment]
Are you sure that you sent a tweet? Can't see anything localization related in my mail nor on the twitter feed. There's a small section about localization in [CONTRIBUTING.md](https://github.com/Lunatrius/InGame-Info-XML/blob/master/CONTRIBUTING.md#localization). Link to the [tool](http://mc.lunatri.us/translate?repo=https://github.com/Lunatrius/InGame-Info-XML).

**Comment by Lunatrius** [comment]
Fixed in a70d126268bbba57f23682e10350111e3a55642b - the new tag is `slimechunk`.

**Comment by hhiru** [comment]
hello! thanks for updating your mod with this nice feature :D I can't see the new tag in taglist tho

**Comment by Lunatrius** [comment]
The last two commits aren't in any release yet. I planned to fix a few other things, but didn't have the time yet. I'll try to get the next build out asap.

**Comment by hhiru** [comment]
oh ok, thank you!
