### ISSUE TITLE
Cyberware's HUD is invisible if IGI is present.

### ISSUE THREAD

**Issue by The-Key** [Lunatrius/InGame-Info-XML#42]
The power HUD from [Cyberware](https://minecraft.curseforge.com/projects/cyberware) doesnt appear if IGI is present. Disabling IGI with the command doesn't fix it either. I've posted this on Cyberware's github too in case it's on their end.

**Comment by Lunatrius** [comment]
Is it hidden even if the IGI overlay is active?

**Comment by The-Key** [comment]
Yes.

**Comment by Lunatrius** [comment]
Unless he's rendering it using the debug event (F3), normal text (usually also on F3) or the potion event when the overlay is disabled in IGI it's most likely on their end then. But I'll have to check their code. Relevant IGI [code](https://github.com/Lunatrius/InGame-Info-XML/blob/151d3890fe6c797e078ac833b4c178a586ae775c/src/main/java/com/github/lunatrius/ingameinfo/handler/Ticker.java#L24-L38).

**Comment by The-Key** [comment]
It does require an "augment" to see the HUD so maybe it is a potion effect. I'll update the cyberware issue with this info, thanks.

**Comment by The-Key** [comment]
I found this in a similar file in the Cyberware repository: [Link](https://github.com/Flaxbeard/Cyberware/blob/master/src/main/java/flaxbeard/cyberware/common/handler/HudHandler.java#L129)
It does mention using the potion icons elementtype.

**Comment by Lunatrius** [comment]
That is definitely it. It uses the potion rendering event to draw it's own HUD and IGI has the *option* to disable the potion overlay by cancelling the event. You can re-enable the potion overlay to (temporarily) fix the issue.

Code wise this can be fixed by using the `net.minecraftforge.fml.common.gameevent.TickEvent` event, `TickEvent.Type.RENDER` particularly.

**Comment by The-Key** [comment]
Thanks a ton man. Enabling potion overlay does fix the issue at the cost of more ugly vanilla hud elements. I've posted this info to the cyberware repo now.
