### ISSUE TITLE
Can't save configs when using custom installation paths

### ISSUE THREAD

**Issue by hhiru** [Lunatrius/InGame-Info-XML#43]
The mod just says "_Something went wrong_". I suspect this is due to the fact I installed forge in a custom path using the Launcher options saving the forge mods in `C:/Users\USER_NAME\AppData\Roaming\.minecraft\forge\forge_1.10.2` instead of installing forge in the main `.minecraft` folder.. Do you think this is a correct assumption? I just entered `/igi save test` in chat and it didn't work :/
![2016-11-16_17 58 28](https://cloud.githubusercontent.com/assets/11262717/20356996/99ebb9b0-ac26-11e6-8f30-25b40f2c4026.png)
![cattura](https://cloud.githubusercontent.com/assets/11262717/20357049/cbb77f42-ac26-11e6-8f88-2a2f23ce3a9f.PNG)

**Comment by Lunatrius** [comment]
I'll need the `logs/fml-client-latest.log` file.

**Comment by hhiru** [comment]
I'm sorry but the game didn't generated any log files to show you.. maybe there is a way to force a debug crash in order to generate a log file?

**Comment by Lunatrius** [comment]
The `logs/fml-client-latest.log` must exist, it's where FML, Forge and most mods log their stuff to.

**Comment by hhiru** [comment]
Ok, I installed forge in the vanilla pack using the Technic launcher, copied all the mods I used and still doesn't work but it finally generated a log file:

[fml-client-latest.zip](https://github.com/Lunatrius/InGame-Info-XML/files/597384/fml-client-latest.zip)

**Comment by Lunatrius** [comment]
Er... the issue is something completely else that I didn't even notice. You have to specify the **full filename**. You can use tab completion to get a list of suggested names.

The file extension (`.xml`, `.json` or `.txt`) is **mandatory** and it used to determine the format of the file.

In your case, `/igi save test.xml` should work properly.

**Comment by hhiru** [comment]
Oh right! I forgot to use the extension.. thanks! Maybe you should add a custom error message for when someone doesn't fill properly the command using no extension. I don't know if this is possible, just a tip :D You added the slime chunk feature I suggested, thanks for your work, again!

**Comment by Lunatrius** [comment]
I have added a warning to the console for this specific issue, I'll be adding more once I rewrite/improve the commands as described in #21

**Comment by Celsiusss** [comment]
> Er... the issue is something completely else that I didn't even notice. You have to specify the **full filename**. You can use tab completion to get a list of suggested names.
> 
> The file extension (`.xml`, `.json` or `.txt`) is **mandatory** and it used to determine the format of the file.
> 
> In your case, `/igi save test.xml` should work properly.

I can't believe that I had to dig that far into the internet to find out that a file extension in required. Maybe give back a more helpful error message than "Something went wrong"?
