### ISSUE TITLE
missing close tag?

### ISSUE THREAD

**Issue by jazzyworld** [Lunatrius/InGame-Info-XML#51]
id like to start by saying thank you, i like having a heads up display of things going on in my world.
that said, there are small issues ive noticed with the latest version (InGameInfoXML-1.11-2.8.1.91-universal.jar), probably related, probably just forgot to close a < / > tag, havent looked at your code, so you decide whats causing it
one... mainhand display name is ALWAYS in the top right
two.. when i looked at the corner alignments, 'bottom right' showed "0 -45", reset to default button confirms this. (this is where im thinking you forgot the close tag, which ended up causing issue one, three, and possibly four)
three.. changing the values in ANY of the alignments DOES NOTHING (probably as a result of issue two)
four... typing '/igi config' only displays the same list as typing '/igi' so i had to code everything by hand in notepad, big WTF /big  (lol) good thing i know a little about this and that so i was able to do what was needed.  if this was intended, kool, no harm done.. but why have '/igi config' ? my guess was its supposed to open a gui of sorts so i dont have to 'tab space space space space < > everything by hand. if it was intended as such, a tutorial would be most helpful for the coding illiterate or newbs

another suggestion... break away from the small numbers on the alignment (0 0)(-2 -2) etc, maybe even decimals would work. 
reason... i have 'show subtitles: on", which uses the 'bottom right' exclusively. so when coding an igi profile, i need to add <                                             > into every line for 'bottom right', just to move everything over away from the right outside border.  for me isnt too hard to overcome, except for window mode, where the igi display is overlapping my hotbar display. having the option (that worked) to set 'bottom right' to "-2 -1.5" would place it just about in the needed postion, away from the edge, leaving the default subtitle display unobstructed. again, if closing the tag fixes the main issue, then this might already be an available option, but until that issue is addressed, all the alignment options are broken and unusable, why is it an option if it doesnt change anything?

**Comment by Lunatrius** [comment]
Incorrect. The offsets are used for the specific anchor points (top left, center, middle right, ....). If you want to move something from the bottom left to the top right you have to move the **tags** themselves into that section (you have to create one if it doesn't exist yet).

`/igi config` is not a valid command. `/igi` (or any *invalid* command) will show a list of valid sub-commands that can be used. Tab auto complete is implemented, so you don't even have to type much.

Decimals won't work, because 1 "unit" is the smallest possible offset on the UI overlay.

**Comment by jazzyworld** [comment]
didnt address any of the issues :/
...the display of the mainhand in the top right covers whatever else is shown there
...the alignment default for bottom right is 0 -45
...setting any alignment value to anything different (0 -2 to 1 1) does nothing

look at your coding, as the title suggests, i think you may have forgotten a closing tag somewhere which is causing these problems

**Comment by Lunatrius** [comment]
Could you provide a screenshot of the issues (where it makes sense)?

**Comment by Lunatrius** [comment]
Closing this due to lack of response.
