### ISSUE TITLE
Out of game taglist? (enhancement)

### ISSUE THREAD

**Issue by Kzitold** [Lunatrius/InGame-Info-XML#52]
Any chance you could provide a readable taglist accessible out of game for those of us who get all our great ideas away from the PC, such as myself at work?
I know the wiki link leads to a taglist, but I've noticed the notice saying it's no longer being kept up to date, so can't rely on it.
Maybe a txt in an unused part of the jar?

**Comment by Kzitold** [comment]
Edit: Nevermind. Found it at "InGameInfoXML-#.#-#.#.#-universal.jar\assets\ingameinfo\lang\en_us.lang" (and the app I use can apparently read it.)

Now I look like an idiot.

**Comment by Lunatrius** [comment]
There used to be a list of all tags outside the game, however that quickly went out of sync because I often forgot to update the wiki page.
