### ISSUE TITLE
taglist command\formatting tags (enhancement)

### ISSUE THREAD

**Issue by Kzitold** [Lunatrius/InGame-Info-XML#53]
Colors, the various forms of highlighting, the obfuscating, and the reset formats.

The taglist does show (or strongly hint) that they are available, but doesn't show how to use them in the info configs.

Maybe instead of "Aqua color (§bEXAMPLE§r)."
you could do "$b (§bAqua color§r)."
(Or however it's done.)

**Comment by Lunatrius** [comment]
Those examples only show the color codes that are used via tags. You can use `{aqua}` instead of `$b` or `§b`.
