### ISSUE TITLE
/igi reload not reloading changed file: intended or bug?

### ISSUE THREAD

**Issue by Squaredude** [Lunatrius/InGame-Info-XML#60]
I was running Minecraft for the first time in a while, and I forgot to copy my old XML in config/, so I did that, and tried to use the command "/igi reload", thinking it would reload the XML file. But it didn't.

Only closing off Minecraft and launching it again loaded the changed XML file.

MC 1.12
Core 1.2.0.40
IGIXML 2.8.1.92
Forge 1.12-14.21.1.2443
MultiMC 0.5.0-945 win32
OS Windows 7 64 bit

**Comment by Lunatrius** [comment]
This is intended. In a new instance the command will try to reload the internal/default config file.

You have to use `/igi load <filename>` first. After that it will load whatever the last loaded config was.

**Comment by Squaredude** [comment]
Gotcha. Thanks for replying and sorry for the bother. :)
