### ISSUE TITLE
Equipped icon and durability now shown

### ISSUE THREAD

**Issue by Protheus** [Lunatrius/InGame-Info-XML#62]
My equippeditem and durability aren't showing suddenly:

![capture](https://user-images.githubusercontent.com/1455178/34157096-62a1a748-e4c0-11e7-83a9-077b43814bb7.JPG)

xml details: https://pastebin.com/SR7Pf8ZL

any idea what i'm doing wrong ?

**Comment by Lunatrius** [comment]
Replace all `equipped*` tags with `mainhand*` tags. The old tags were confusing and were removed in 1.12.

**Comment by Protheus** [comment]
Thank you
