### ISSUE TITLE
Date Tag

### ISSUE THREAD

**Issue by Aryezz** [Lunatrius/InGame-Info-XML#69]
While there is a tag for real time (rltime12 / rltime24) there is no date tag that i am aware of.

I would find that feature highly useful, because i could see the date & time a screenshots in the screenshots itself.

**Comment by Lunatrius** [comment]
You can use the `formattedtime` fuction. It uses Java's [SimpleDateFormat](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html).
```xml
<formattedtime>
    <str>dd.mm.yyyy</str>
</formattedtime>
```

**Comment by Aryezz** [comment]
Oh thanks for the tip, i didnt know that.
Ill cloes this now :)
